### ISSUE TITLE
Navigation issue

### ISSUE THREAD

**Issue by zxy51320** [ASCENDynamics-NFP/AscendCoopPlatform#116]
## Description
Navigation to User Profile Fail
## Steps to Reproduce

1. Open page "https://ascendcoopplatform-dev.web.app/user-login"
2. Click on 'Create Account'
3. Click on 'Login' from the left pane
4. Then Click on 'Login with Google'

## Expected Behavior

When finishing login with Google, page should be navigated to User Profile.

## Actual Behavior

Right half of the page stays on Login

## Screenshots (Optional)

<img width="1274" alt="截屏2023-08-14 下午5 00 47" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/78584947/6d1221dd-c0db-4c20-8797-706dbc78d064">
## Environment (Optional)

- OS: macOS 13.5 (22G74)
- Browser (if applicable): Chrome
- Version (if applicable): 115.0.5790.170

**Comment by mufniarz** [comment]
Thank you for finding this.  I did not think to test this behavior.
