### ISSUE TITLE
Search result remains after switching user

### ISSUE THREAD

**Issue by zxy51320** [ASCENDynamics-NFP/AscendCoopPlatform#117]
## Description

Search result remains after switching user.

## Steps to Reproduce

List the steps to reproduce the behavior:

1. Login with User1
2. Search on Groups and Users
3. Logout User1
4. Login with User2
5. Check out Groups tag and Users tag

## Expected Behavior

Search results should be cleaned up.
<img width="1253" alt="截屏2023-08-14 下午5 30 38" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/78584947/85278c80-ad2a-40e0-83ab-8aeabb0dea64">

## Actual Behavior

Search result remains after switching user.

## Environment (Optional)

OS: macOS 13.5 (22G74)
Browser (if applicable): Chrome
Version (if applicable): 115.0.5790.170

**Comment by mufniarz** [comment]
Thank you for finding this.  This looks like it could have been a pretty big privacy issue.
