### ISSUE TITLE
Unable to search users: Missing or insufficient permissions

### ISSUE THREAD

**Issue by zxy51320** [ASCENDynamics-NFP/AscendCoopPlatform#121]
## Description

Unable to search users: Missing or insufficient permissions

## Steps to Reproduce

List the steps to reproduce the behavior:

1. Go to Users tag
2. Enter key words then search

## Expected Behavior

Search successfully

## Actual Behavior

Unable to search users: Missing or insufficient permissions

## Screenshots (Optional)

<img width="1275" alt="截屏2023-08-16 上午11 19 52" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/78584947/96d92378-b175-4446-8c21-85abb17bfbb7">
## Environment (Optional)

OS: macOS 13.5 (22G74)
Browser (if applicable): Chrome
Version (if applicable): 115.0.5790.170

**Comment by mufniarz** [comment]
Hey, sorry about this. I updated the security rules, but the code hasn't been deployed in yet. I'll merge that in now.

**Comment by mufniarz** [comment]
The way that Security Rules work is that they throw that error if you're query isn't limiting the records you pull.  So both the app and the backend needs to be setup to limit records, or we run into this error.

**Comment by mufniarz** [comment]
Yeah, need to reach out to UX to see how they want to address landing on a Profile that is set to private.  I've merged in the latest code and I think it should resolve this issue.
