### ISSUE TITLE
Dev: Insecure Transmission of Password in Login and Registration Requests

### ISSUE THREAD

**Issue by zxy51320** [ASCENDynamics-NFP/AscendCoopPlatform#132]
## Description
Password is not encrypted in the request when the user is trying to login or signup.

## Expected Behavior
The password is encrypted in the request.

## Actual Behavior
The password is not encrypted in the request.

## Screenshots (Optional)
![未命名](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/78584947/3bd6d79a-c69d-4cc6-8fb9-55e2dcda1bf4)

**Comment by malsmr** [comment]
Is this ready to be worked on?

**Comment by mufniarz** [comment]
@malsmr I'm not sure, it would be good to have someone look into how to resolve this.  The only problem is that I've done so much refactoring to the codebase in another branch that I'm not sure what kinds of conflicts it would result in with this work.  Also I'm not sure if my refactoring work is currently breaking the backend.  I may need a few days to wrap up with my current work before this could be worked on.

**Comment by malsmr** [comment]
Ok np

**Comment by mufniarz** [comment]
@zxy51320 sorry I didn't have a chance to really look at this before, but there's no way to secure this.  This is all data that's being passed to the backend.  I think as long as we're using HTTPS it should be secure in transit, but prior to that, it's data the user enters, besides hiding form prying eyes, there's no transforming it on the frontend.  I'm going to close this as a non-issue.
