### ISSUE TITLE
Tasks <> Create an Account and Log In/Out

### ISSUE THREAD

**Issue by Nyero2023** [ASCENDynamics-NFP/AscendCoopPlatform#144]
### Tasks
- [ ] #145
- [ ] #146
- [ ] #147
- [ ] https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/discussions/9#discussioncomment-5892269
- [ ] #152
- [ ] Test backend API endpoints for user registration, login, and logout.

**Comment by mufniarz** [comment]
I'm closing this task, as I've linked all these items to their parent story in their description.  All of these should a direct link to the feature story now.
