### ISSUE TITLE
[BED] Implement Popup Modal for Privacy Policy and Terms of Use, and Add Checkbox to Signup Page

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#187]
#### Description
To enhance user awareness and ensure legal compliance, we need to implement a popup modal that displays our "Privacy Policy" and "Terms of Use" agreements. Additionally, we should include a checkbox on the signup page that users must check to indicate their agreement to these terms.

Create component in `app/shared/components` directory.

#### Developer Tasks
- [x] Create a popup modal component that can display text content.
- [ ] Ensure the modal is accessible and can easily be closed.
- [x] Add content for the "Privacy Policy" and "Terms of Use" in the modal. This content should be easily updatable.
- [ ] On the signup page, add a checkbox with text such as "I have read and agree to the Privacy Policy and Terms of Use."
- [ ] The signup button should be disabled until the user checks the agreement box.
- [ ] Ensure the modal links and checkbox are clearly visible and easy to interact with.
- [ ] Implement a mechanism to record user acceptance of these terms.

#### Testing Notes:
1. **This functionality is on the Sign Up page. Please use this link to test:  https://ascendcoopplatform-dev.web.app/signup**
2. **Use these links to verify or manipulate data:**
- Link to user accounts/emails:  https://console.firebase.google.com/u/2/project/ascendcoopplatform-dev/authentication/users
- Link to Firestore Database:  https://console.firebase.google.com/u/2/project/ascendcoopplatform-dev/firestore/data/~2Faccounts~2F2lqqbtGq89W8beumG8JIm56x4Em2

#### Acceptance Criteria

- [x] 1. Users can view the "Privacy Policy" and "Terms of Use" in a popup modal by clicking the links provided on the signup page.
- [x] 2. Users must check a box on the signup page to agree to these terms before creating an account.
X 3. The implementation should be accessible and comply with web standards.
X 4. The feature works on all major browsers and devices.

****Did not verify Development Tasks or AC 3 or 4.**  Please see the [Testing Notes comment](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/issues/187#issuecomment-1974748944).**

#126 - contains text for `Terms of Use`
#127 - contains text for `Privacy Policy`

**Comment by quakermiss** [comment]
**Testing Notes:**

> Questions/Bugs:
1. @mufniarz , please see the Assumptions section to ensure the following:
> 1. All Developer Tasks have been completed.
> 2. 1. Someone with a legal and English background reviews text for Privacy Policy and Terms of Use.
> 3. Accessibility, browser, and device testing are in their own ticket(s).

> General:
1. Tested on Windows 11 PC, Chrome browser version 122.0.6261.94
2. Tested in the dev environment
3. Used link:  https://ascendcoopplatform-dev.web.app/signup

> Assumptions:
1. All Developer Tasks have been completed, regardless of whether they are checked or unchecked.
2. Only tested that the checkbox, Privacy Policy, and Terms of Use work.  Text in the Privacy Policy and Terms of Use was not verified.
3. Accessibility, additional browser, and device testing are included in a separate ticket(s) and will be done before implementation; Acceptance Criteria 3 & 4.
> 1.  (3) The implementation should be accessible and comply with web standards.
> 2.  (4) The feature works on all major browsers and devices.

> Acceptance Criteria:
1. Verified that Users can view the "Privacy Policy" and "Terms of Use" in the popup modal by clicking the links on the signup page.
2. Verified that Users must check the box on the signup page to agree to these terms before creating an account.
3. Verified that the checkbox, Privacy Policy, and Terms of Use are accessible by mouse only.
4. Verified that checkbox, Privacy Policy, and Terms of Use work on Chrome and Windows 11.

**Results of Testing:**
Passed.

**Comment by mufniarz** [comment]
@quakermiss this looks good, the only thing I ask is that you close this ticket once you're finished with it.  Let me know if you don't have that option.
