### ISSUE TITLE
Create wireframes and user flow outlining user journeys for group creation.

### ISSUE THREAD

**Issue by Nyero2023** [ASCENDynamics-NFP/AscendCoopPlatform#200]
#### Description:
The task involves developing visual representations, namely wireframes and flowcharts, to outline the user experience and system processes associated with the group creation feature. This process is critical in providing a structured and intuitive user interface while also elucidating the logical flow of actions and system responses.

#### Related Feature/Story:
Link to the feature or user story that this task is part of:
- [ ] [Link to related feature #198]

#### Acceptance Criteria:
List the specific criteria that define when this task is completed. What exactly needs to be achieved for this task to be considered done?
1. User research and requirements gathering; conduct interviews or surveys to understand user needs for group creation.
2. Identify key user flows: Map out primary user journeys for group creation and organizational structuring.
3. Develop low-fidelity wireframes for each step of the user journey.
4. Develop high-fidelity wireframes.

#### Technical Details (if applicable):
Provide any technical details, code snippets, or references necessary for completing this task. Include information about APIs, libraries, or specific coding standards to follow.

#### Design Specifications (if applicable):
Attach or link to any design mockups, diagrams, or specifications that are relevant to this task.

#### Dependencies:
1. The availability of branding guidelines is essential to maintain consistency and align the wireframes with the overall visual identity.
2. A clear understanding of business requirements is necessary to ensure that the wireframes address specific organizational needs related to group creation and structuring.

#### Due Date (if applicable):
TBD

#### Notes:
Add any additional notes or comments that might be helpful for the person working on this task.

**Comment by mufniarz** [comment]
Closing this as I believe we've past this phase already for user and group creation.
