### ISSUE TITLE
Design visual mockups and interactive prototypes.

### ISSUE THREAD

**Issue by Nyero2023** [ASCENDynamics-NFP/AscendCoopPlatform#201]
#### Description:
The task involves creating visual mockups and interactive prototypes for the user interface. This includes crafting high-fidelity designs and simulated user interactions to provide a tangible representation of the final user experience.

#### Related Feature/Story:
_Link to the feature or user story that this task is part of:_
- [ ] [Link to related feature #198]

#### Acceptance Criteria:
1. Interactive prototyping: Translate static designs into interactive prototypes using tools like Figma, Sketch, or Adobe XD.
2. Conduct usability testing using the prototype.

#### Technical Details (if applicable):
_Provide any technical details, code snippets, or references necessary for completing this task. Include information about APIs, libraries, or specific coding standards to follow._

#### Design Specifications (if applicable):
_Attach or link to any design mockups, diagrams, or specifications that are relevant to this task._

#### Dependencies:
1. User availability for usability testing. Coordinating usability testing depends on the availability of users who are ready to participate and give feedback.

#### Due Date (if applicable):
TBD

#### Notes:
_Add any additional notes or comments that might be helpful for the person working on this task._

**Comment by mufniarz** [comment]
@Nyero2023 I'm going to close this item out as it seems like it's made for the profile pages. I think we've already addressed mockups for those and as it doesn't specify specific features I'm going to assume that we've already finished this.
