### ISSUE TITLE
Functional Testing

### ISSUE THREAD

**Issue by Nyero2023** [ASCENDynamics-NFP/AscendCoopPlatform#202]
#### Description:
Functional testing is a critical phase where the group creation functionalities are systematically evaluated to ensure they align with specified requirements. This task involves thoroughly assessing the various features and components of the system to validate that they perform as intended and meet user expectations.

#### Related Feature/Story:
_Link to the feature or user story that this task is part of:_
- [ ] [Link to related feature #198]

#### Acceptance Criteria:
_List the specific criteria that define when this task is completed. What exactly needs to be achieved for this task to be considered done?_
1. Develop comprehensive test cases based on functional specifications and user stories.
2. Configure the testing environment to mirror the production setup.
3. Execute the prepared test cases to verify the functionality of each component.
4. Conduct integration testing and user interface testing.
5. Assess how the system handles errors and exceptions.
6. Verify the system's responsiveness and stability under different load conditions.

#### Technical Details (if applicable):
_Provide any technical details, code snippets, or references necessary for completing this task. Include information about APIs, libraries, or specific coding standards to follow._
Draft Test Plan: https://docs.google.com/document/d/13pvFOipWQNsnKKQiHEwvZlgfAy76ECOW3XTClUs5mIM/edit?pli=1

#### Design Specifications (if applicable):
_Attach or link to any design mockups, diagrams, or specifications that are relevant to this task._

#### Dependencies:
1. Availability of clear and detailed functional requirements: Testing relies on well-defined specifications to ensure accurate validation of functionality.
2. Completion of development for the features being tested.
3. Availability of a suitable test environment.
4. Priority of features and the overall project schedule: Functional testing needs to align with project timelines and prioritize critical functionalities.

#### Due Date (if applicable):
TBD

#### Notes:
Add any additional notes or comments that might be helpful for the person working on this task.

**Comment by mufniarz** [comment]
There's a duplicate issue for unit testing functionality. I'm going to close this one.
