### ISSUE TITLE
Implement User Registration Form - Section 1: Account Credentials

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#204]
#### Description:
Implement the first section of the user registration form, which includes collecting the user's email address and password, enforcing password requirements, and including terms of use and privacy policy confirmation.

#### Related Feature/Story:
Link to the feature or user story that this task is part of:
- [x] https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/issues/203

#### Acceptance Criteria:
- **Email Address Field:** 
  - Input field for the user's email address.
  - Validate for a proper email format.

- **Password Field:**
  - Input field for the user's password.
  - Display password requirements near the field.

- **Password Requirements:**
  - Minimum 8 characters.
  - Must include at least one uppercase letter, one lowercase letter, one numeric digit, and one special character.
  - Allowed special characters: `~!@#$%^&*-_+=[]{}|/;:,.?`
  - Implement real-time validation and indicate whether the entered password meets the requirements.

- **Confirm Password Field:**
  - Input field for confirming the password.
  - Ensure it matches the password entered in the Password field.

- **Terms of Use and Privacy Policy Confirmation:**
  - Include checkbox for terms of use and privacy policy agreement.  
    - Message: `I have read and agree to the Terms of Use and Privacy Policy.`
      - [Privacy Policy](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/wiki/Privacy-Policy-%E2%80%90-ASCENDynamics-NFP-Collaborative-Nonprofit-Network)
      - [Terms of Use](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/wiki/Terms-of-Use-%E2%80%90-ASCENDynamics-NFP-Collaborative-Nonprofit-Network-(CNN))
  - The user must check this box to proceed with registration.
  
- **Update `account` Schema:**
  - Schema will be updated in a different ticket.

#### Technical Details (if applicable): 
- Use HTML and CSS for the form layout.
- Implement JavaScript or relevant backend logic for validation.
- Design should be responsive and consistent with existing UI.

#### Design Specifications (if applicable):
No design details, please use the current style.

#### Dependencies:
      - [Privacy Policy](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/wiki/Privacy-Policy-%E2%80%90-ASCENDynamics-NFP-Collaborative-Nonprofit-Network)
      - [Terms of Use](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/wiki/Terms-of-Use-%E2%80%90-

#### Notes:
This ticket is mainly for adding validations to the password field, terms of use and privacy policy, and an additional confirm password field to validate against.   This should all be validated on the `user-signup` page.

**Comment by mufniarz** [comment]
Including edge case requirements:

**Edge Cases**
Edge Cases for Registration
- Duplicate Email/Username:
  - User attempts to register with an email/username that already exists in the system.
  - The system should provide a clear error message prompting the user to choose a different email/username.
- Invalid Email Format:
  - User enters an email address with an incorrect format during registration.
  - The system should validate the email format and provide a helpful error message guiding the user to enter a valid email address.
- Weak Password:
  - User tries to register with a password that does not meet the platform's security requirements.
  - The system should enforce password strength rules and communicate them clearly to the user.
- Incomplete Registration Form:
  - User submits the registration form with missing or incomplete mandatory fields.
  - The system should highlight the missing fields and guide the user to complete the form before proceeding.

**Comment by bellom** [comment]
@mufniarz - Everything seems ok with this ticket.  Tested by @bellom @Ibingo44
