### ISSUE TITLE
[BED] Create Registration Page with Account Type Selection

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#205]
#### Description:
The task involves creating a new registration page located in `src/app/modules/account/pages/registration`. This page will allow users to choose between registering a User or a Group account. Based on the user's selection, the page will display the appropriate registration form: either the register group component or the register user component. This functionality is essential to streamline the account creation process and provide a user-friendly experience for different types of accounts.

#### Related Feature/Story:
- [ ] https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/issues/203

#### Testing Notes:
1. **Please add a brand new user(s) to test this functionality.**
2. **Use these links to verify or manipulate data:**
- Link to user accounts/emails:  https://console.firebase.google.com/u/2/project/ascendcoopplatform-dev/authentication/users
- Link to Firestore Database:  https://console.firebase.google.com/u/2/project/ascendcoopplatform-dev/firestore/data/~2Faccounts~2F2lqqbtGq89W8beumG8JIm56x4Em2

#### Acceptance Criteria:
- [x]  1. A new registration page is created at `src/app/modules/account/pages/registration.`
- [x]  2. The page includes an option for the user to select the type of account they wish to create (User or Group).
- [x]  3. Based on the selection, the appropriate registration form (register group component or register user component) is displayed.
X 4. The user interface is intuitive and user-friendly.
X 5. The page is responsive and works well on both desktop and mobile devices.
****Did not verify AC 4 or 5, Technical Details, Design Specifications, Dependencies or Notes.  Please see the [Testing Notes comment] https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/issues/205#issuecomment-1976557493.**

#### Technical Details:
- Implement the page using the existing project structure and coding standards.
- Ensure that the components are modular and reusable.
- Use appropriate routing to navigate to the registration page.

#### Design Specifications:
- Design mockups for the registration page should align with the project's existing style guide.
- (Attach or link to any specific design mockups or UI/UX guidelines for this page.)

#### Dependencies:
- This task may depend on the completion of the individual register group and register user components.
- Ensure that the routing and state management in the application are set up to handle the new registration flow.

#### Notes:
- Consider implementing client-side validation for the initial account type selection.
- Ensure that the page includes appropriate error handling and user feedback mechanisms.

#### Rough outline of the desired page:
<img width="623" alt="image" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/7826550/0bb46201-d28b-4e8d-946c-fefaa90a1b1f">

**Comment by Nyero2023** [comment]
Hey, @quakermiss what do you mean by `Related Feature/Story Registration and Log In/Out 203 has not been completed or tested.`
I'd like to understand which related features/story you are talking about here.

**Comment by quakermiss** [comment]
@Nyero2023 There's a section in this ticket called _Related Feature/Story_  section.  See the screenshot below or the **Description** at the top of this ticket.  

Ticket 203s status is **In Progress** and is still in development (being coded).  When you click on the link to 203, it lists all the features.


![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/100221950/3ac1efe6-20af-4f4c-a8dd-e59aeaf1cd89)

**Comment by bellom** [comment]
**Issue 2:**

@mufniarz - For some reason, we didn't find Nigeria's phone code (+234), and we think there might be more countries missing.


![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/9d775af3-1108-40fe-9818-48b80bfdc1cf)

**Comment by bellom** [comment]
**Issue 3:**

@mufniarz The form only contains US states. Users should be able to pick their states according to the selected country.

![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/ccda88d9-62da-4752-9921-e5fcdb4b6089)

**Comment by bellom** [comment]
@mufniarz - Everything seems ok with this ticket.  Tested by @bellom @Ibingo44

**Comment by mufniarz** [comment]
The registration page was created a while back.  I'm going to close this out as complete.
