### ISSUE TITLE
[BED] Create User Registration Component

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#207]
#### Description:
The task involves creating a new component for user registration. This component is essential for the user onboarding process, allowing individuals to create their profiles on the platform. The form will collect contact information, including phone number, alternate email, and mailing address, as well as professional information like occupation, employer name, work experience, skills, current job title, LinkedIn profile, and educational background.

#### Related Feature/Story:
- [ ] https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/issues/203

#### Testing Notes:
1. **Please add a brand new user(s) to test this functionality.**
2. **Use these links to verify or manipulate data:**
- Link to user accounts/emails:  https://console.firebase.google.com/u/2/project/ascendcoopplatform-dev/authentication/users
- Link to Firestore Database:  https://console.firebase.google.com/u/2/project/ascendcoopplatform-dev/firestore/data/~2Faccounts~2F2lqqbtGq89W8beumG8JIm56x4Em2

#### Acceptance Criteria:
1. A new 'User Registration' component is created.
2. The component includes fields for:
   - Name (Required)
   - Tagline (Required)
   - Description (Required)
   - Phone Number (Optional)
   - Alternate Email (Optional)
   - Mailing Address (Optional)
   - Emergency Contact Number (Optional)
   - Preferred Method of Contact (Dropdown with options like Email, Phone, Text)
4. The form includes validation for required fields.
5. The component is styled according to the project's design guidelines.
6. The component is responsive and functions correctly on both desktop and mobile devices.

#### Technical Details:
- The component should live in `src/app/modules/account/pages/registration/components/user-registration`.
- Implement form validation, especially for fields like phone number and email.
- Use appropriate controls for each field, such as dropdowns for 'Preferred Method of Contact'.
- Integrate the component with the backend to handle form submission.

#### Design Specifications:
- Follow the project's UI/UX design principles.
- Ensure the form is user-friendly and accessible.

#### Dependencies:
- This component may depend on backend APIs for user registration.
- Integration with other user profile features, if applicable.
- Registration Page: #205 

#### Notes:
- Ensure robust error handling and user feedback for the form submission process.

**Comment by bellom** [comment]
The list of issues below also applies to Group registration.

**Issue 1: under User registration**
@mufniarz - We think this text field should be invalid if the user didn't use a URL, kindly check the screenshot below;

![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/bddf9627-839e-40bf-9737-77645673cf80)

**Comment by bellom** [comment]
**Issue 3:**

@mufniarz The dropdown in the form only contains US states. Users should be able to pick their states according to the selected country.

![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/ccda88d9-62da-4752-9921-e5fcdb4b6089)

**Suggestion:** The dropdown for the country should come first before the state.

**Comment by mufniarz** [comment]
@bellom for Issue 2, we don't really have specific countries we're supporting.  The only one we're supporting is United States at the moment.
Issue 3, I agree but since we're only supporting the US at the moment, I think we can hold off on this until we identify which other countries we'll be supporting.

**Comment by mufniarz** [comment]
I've made these updates in my latest branch and will close this ticket.
