### ISSUE TITLE
[FED] User Account Profile Page 

### ISSUE THREAD

**Issue by bellom** [ASCENDynamics-NFP/AscendCoopPlatform#231]
#### Description:
The task involves creating a user account profile page as it is in the [Figma](https://www.figma.com/file/lYVceBnSazc8274SLKQO4D/ASCENDynamic?type=design&node-id=840-9&mode=design&t=YHHjPGnHhnxc0wud-0) design.
This component is essential for the user onboarding process, allowing individuals to create their profiles on the platform. The form will collect contact information, including phone number, alternate email, and mailing address, as well as professional information like occupation, employer name, work experience, skills, current job title, LinkedIn profile, and educational background.

#### Related Feature/Story:
- [ ] [Link to related Feature #203]
- [ ] [Link to related Task #233]

#### Acceptance Criteria:
1. A User Registration profile design is created.
2. The component includes fields for:
   - Profile Section:
     - Name
     - Description
     - Website
     - Social media
     - Tagline
    - Contact  Information
       - Phone Number
       - Email Address
       - Mailing Address 
       - Preferred Method of Contact
    - Professional  Contact
      - Occupation
      - Employer  Name
      - Skills and Expertise
      - Educational  Background
    - Friends
    - Organizations
    - Volunteer Preferences
       - Area of interest
       - Availability
       - Preferred Volunteer Roles
       - Willingness to travel
       - Level of Commitment
    - Labor Rights
      - Union membership
      - Workplace concerns
      - Preferred  advocacy  areas
      - Experience with labor rights issues

#### Feature:
Edit button (with pencil icon) - When the user clicks on the edit button, edit pages should open.
<img width="156" alt="image" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/f943382b-5512-45e7-abd7-493b6645e16e">

#### Technical Details (if applicable):
Provide any technical details, code snippets, or references necessary for completing this task. Include information about APIs, libraries, or specific coding standards to follow.

#### Design Specifications (if applicable):
[Figma](https://www.figma.com/file/lYVceBnSazc8274SLKQO4D/ASCENDynamic?type=design&node-id=840-9&mode=design&t=YHHjPGnHhnxc0wud-0) design.

#### Dependencies:
Note any dependencies this task has on other tasks or components. Indicate if other work needs to be completed before this task can be started.

#### Due Date (if applicable):
If the task has a specific deadline, indicate the due date.

#### Notes:
The design should closely match the one in Figma. Please refer to the screenshot below for details;
<img width="338" alt="image" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/45be565b-ea27-4158-8101-83a291292d55">

**Comment by bellom** [comment]
Design correction:
<img width="338" alt="image" src="https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/45be565b-ea27-4158-8101-83a291292d55">

@mufniarz - this new correction is missing the edit button, if it was intentional, please ignore it.

**Comment by mufniarz** [comment]
It looks like this was mainly completed and the section that wasn't was moved to the next milestone.  I'm going to close this out as complete.
