### ISSUE TITLE
Implement Contact Information Section

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#235]
#### Description:
Create a Contact Information section for the User Account Profile Page to display the user's contact details such as phone number, email address, mailing address, and preferred method of contact. This section should provide a clear and user-friendly interface for users to view contact information easily.

#### Related Feature/Story:
- [User Account Profile Page #231](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/issues/231)

#### Acceptance Criteria:
1. Implement a visually appealing and intuitive UI design for the Contact Information section.
2. Ensure consistency with the overall design language and style of the User Account Profile Page.
3. Include separate fields for displaying the user's phone number, email address, mailing address, and preferred method of contact.
4. Provide clear labels for each field to indicate the type of contact information.

#### Technical Details (if applicable):
- Utilize HTML5 and CSS3 for frontend design.
- Ensure fields are responsive and accessible according to WCAG 2.1 guidelines.
- Backend integration for storing data should use RESTful APIs.

#### Design Specifications (if applicable):
- Adhere to the UI/UX design as specified in the project’s [Figma file](https://www.figma.com/file/lYVceBnSazc8274SLKQO4D/ASCENDynamic?type=design&node-id=0%3A1&mode=design&t=rmsd3enHKEjlYwuo-1). Ensure the design is responsive and accessible, and also see the screenshot below;
- ![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/648af6a4-0260-4fd6-813c-1929ffaced3b)

#### Dependencies:
- This task depends on the completion of the initial user database setup.
- Must align with the overall styling defined in the Figma design.

#### Due Date (if applicable):
- [Specify Due Date Here]

#### Notes:
- Make sure the Contact Information section is responsive and displays properly on various devices and screen sizes (desktop, tablet, mobile).
- Reference the Figma link for exact design specifications and layout.

**Comment by mufniarz** [comment]
@joaopedro04 @bellom it's best if we complete the edit form first before working on these components.  It'll just make it easier if there's a way to add data on the application first.

**Comment by bellom** [comment]
I agree with you 👍.

**Comment by mufniarz** [comment]
@bellom @joaopedro04 I've created the Contact Info Form and merged it in.  I've updated the data model so that we take in multiple addresses now.  Just be aware, but you're free to continue with this component.
