### ISSUE TITLE
Labor Rights Form Section

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#244]
#### Task Description:
Develop the form component for the "Labor Rights Section" on the Edit Profile page. This component will allow users to edit and save their union membership status, workplace concerns, preferred advocacy areas, and experiences with labor rights issues.

#### Related Feature/Story:
- [Edit Page - Profile #233](https://github.com/orgs/ASCENDynamics-NFP/projects/1/views/1?pane=issue&itemId=61365432)

#### Acceptance Criteria:
1. The form must include checkboxes for union membership.
2. Text input fields for workplace concerns and preferred advocacy areas.
3. Textarea for detailing experiences with labor rights issues.
4. Integration with backend APIs for data fetching and updating.
5. Ensure all inputs are validated before submission to maintain data integrity.
6. User feedback on successful save or error.

#### Technical Details (if applicable):
- Implement the form using HTML forms, CSS for styling, and JavaScript for front-end logic.
- Utilize RESTful API calls to get and post data to the server.

#### Design Specifications (if applicable):
Adhere to the UI/UX design as specified in the project’s [Figma file](https://www.figma.com/file/lYVceBnSazc8274SLKQO4D/ASCENDynamic?type=design&node-id=0%3A1&mode=design&t=rmsd3enHKEjlYwuo-1). Ensure the design is responsive and accessible, also see the screenshot below;

![Image](https://github.com/ASCENDynamics-NFP/AscendCoopPlatform/assets/31897434/252527c6-035b-4eaf-b6a5-3cd8e1753f0f)

#### Dependencies:
This task depends on the API endpoints for labor rights data being fully operational.

#### Due Date (if applicable):
[Specify due date, if applicable]

#### Notes:
Please ensure that the form component is user-friendly and test it across different devices for responsiveness. The functionality should seamlessly integrate with the overall profile editing experience.

**Comment by Vayras** [comment]
@mufniarz I would like to contribute towards this issue.

**Comment by mufniarz** [comment]
@Vayras sorry for the late response, I didn't notice your comment till I started looking at this issue. Feel free to pick this up if you have capacity Vayras.  There are examples of how these components should be built if you look at contact-info, basic-info, professional-info components.  If you have any questions feel free to ask @bellom or @mufniarz.

**Comment by mufniarz** [comment]
If we don't hear back from @Vayras, I may just quickly knock this out.
