### ISSUE TITLE
Update header in README.md to read "Ascend Co-op Platform"

### ISSUE THREAD

**Issue by mufniarz** [ASCENDynamics-NFP/AscendCoopPlatform#46]
## Description

The README.md file currently reads "AscendCoopPlatform" update this to "Ascend Co-op Platform".

## Location

README.md header

## Proposed Changes (Optional)

Update text "AscendCoopPlatform" to "Ascend Co-op Platform"

**Comment by Nikko-Adrian-Pacleb** [comment]
Hi, I am new to open source and I would like to try and do this issue.
